### ISSUE TITLE
bootcmd always overwritten on tqmls1028a when the env is in MMC

### ISSUE THREAD

**Issue by AlbanBedel** [tq-systems/u-boot-tqmaxx#3]
When running from SD/eMMC on a tqmls1028a the `bootcmd` environment get overwritten at every boot. This is due to a bug in arch/arm/cpu/armv8/fsl-layerscape/soc.c board_late_init() which fails badly in combination with MMC redundant environment.
I would suggest fixing board_late_init() as in the following  [patch](https://lists.denx.de/pipermail/u-boot/2020-November/432943.html).

**Comment by tq-niebelm** [comment]
@gregorHerburger Please check if this is fixed. Maybe we can close this?

**Comment by tq-gregorHerburger** [comment]
Fixed with: https://github.com/tq-systems/u-boot-tqmaxx/commit/439b47b24091afe3cec1abb1fe720750956fbbfe
